stages:
  - export
  - report
  - deploy

variables:
  EXPORT_NAME: Wool

.export:
  stage: export
  image: barichello/godot-ci:4.5.1
  before_script:
    - apt-get update && apt-get install -y curl
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - mv .secure_files/release.keystore release.keystore

  script:
    - mkdir -p $(dirname ${EXPORT_PATH})
    - godot --headless --verbose --export-${EXPORT_TYPE} "${PRESET_NAME}" ${EXPORT_PATH}
    - echo "success" > build/${PLATFORM}/success
  artifacts:
    name: ${EXPORT_NAME}-${PLATFORM}
    paths:
      - build/${PLATFORM}
    expire_in: 1 week

.deploy:
  stage: deploy
  only:
    - main

.artifacts-settings:
  artifacts:
    paths:
      - public
    expire_in: 1 week

export-web:
  extends: .export
  variables:
    PLATFORM: web
    PRESET_NAME: Web
    EXPORT_PATH: build/web/index.html
    EXPORT_TYPE: release

export-android:
  extends: .export
  variables:
    PLATFORM: android
    PRESET_NAME: Android
    EXPORT_PATH: build/android/${EXPORT_NAME}.aab
    EXPORT_TYPE: release

export-android-apk:
  extends: .export
  variables:
    PLATFORM: android-apk
    PRESET_NAME: Android APK
    EXPORT_PATH: build/android-apk/${EXPORT_NAME}.apk
    EXPORT_TYPE: release

export-windows:
  extends: .export
  variables:
    PLATFORM: windows
    PRESET_NAME: "Windows Desktop"
    EXPORT_PATH: build/windows/${EXPORT_NAME}.exe
    EXPORT_TYPE: release

generate-badges:
  extends:
    - .artifacts-settings
  stage: report
  image: python:3.11-alpine
  script:
    - python3 scripts/tools/update_version_json.py
  only:
    - main

pages:
  extends:
    - .deploy
    - .artifacts-settings
  image: alpine
  dependencies:
    - export-web
    - generate-badges
  script: |
    cp -r build/web/* public/
    echo '/*' > public/_headers
    echo '  Cross-Origin-Embedder-Policy: require-corp' >> public/_headers
    echo '  Cross-Origin-Opener-Policy: same-origin' >> public/_headers

deploy-android:
  extends: .deploy
  image: ruby:3.2
  before_script:
    - gem install fastlane
  script:
    - fastlane android deploy
