stages:
  - export
  - deploy

variables:
  EXPORT_NAME: wooly

.export:
  stage: export
  image: barichello/godot-ci:4.5.1

  script:
    - mkdir -p $(dirname ${EXPORT_PATH})
    - godot --headless --verbose --export-${EXPORT_TYPE} "${PRESET_NAME}" ${EXPORT_PATH}
  artifacts:
    name: ${EXPORT_NAME}-${PLATFORM}
    paths:
      - build/${PLATFORM}
    expire_in: 1 week

export-web:
  extends: .export
  variables:
    PLATFORM: web
    PRESET_NAME: Web
    EXPORT_PATH: build/web/index.html
    EXPORT_TYPE: release

export-android:
  extends: .export
  variables:
    PLATFORM: android
    PRESET_NAME: Android
    EXPORT_PATH: build/android/${EXPORT_NAME}.aab
    EXPORT_TYPE: release

export-windows:
  extends: .export
  variables:
    PLATFORM: windows
    PRESET_NAME: "Windows Desktop"
    EXPORT_PATH: build/windows/${EXPORT_NAME}.exe
    EXPORT_TYPE: release

pages:
  stage: deploy
  image: alpine
  dependencies:
    - export-web
  script: |
    mkdir -p public
    cp -r build/web/* public/
    echo '/*' > public/_headers
    echo '  Cross-Origin-Embedder-Policy: require-corp' >> public/_headers
    echo '  Cross-Origin-Opener-Policy: same-origin' >> public/_headers
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main

deploy-android:
  stage: deploy
  image: ruby:3.2
  dependencies:
    - export-android
  before_script:
    - gem install fastlane
  script:
    - fastlane supply --aab build/android/${EXPORT_NAME}.aab --track internal --package_name com.florentinerge.wooly --json_key "$PLAY_STORE_JSON_KEY" --skip_upload_metadata --skip_upload_images --skip_upload_screenshots --release_status draft
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $PLAY_STORE_JSON_KEY